# $HOME/.zshenv
#
# ZSH Environment Variables and Exports
#
# export PATH=$PATH:/usr/local/opt/python@3.9/libexec/bin
# export TRACE="$TRACE\n$BASH_SOURCE --> $(realpath $BASH_SOURCE)"

export ZSH_HIGHLIGHT_HIGHLIGHTERS_DIR=/usr/local/share/zsh-syntax-highlighting/highlighters
#
export PATH=$PATH:~/.bin

export PATH=$PATH:/usr/local/texlive/2022basic/bin/universal-darwin

export MYVIMRC=~$HOME/.vim/vimrc.vim

export ZSH_HIGHLIGHT_HIGHLIGHTERS_DIR=/opt/homebrew/share/zsh-syntax-highlighting/highlighters

export HOMEBREW_NO_ANALYTICS=1
