# $HOME/.zshenv
#
# ZSH Environment Variables and Exports
#
# export PATH=$PATH:/usr/local/opt/python@3.9/libexec/bin
# export TRACE="$TRACE\n$BASH_SOURCE --> $(realpath $BASH_SOURCE)"
# export HOMEBREW_PATH=/opt/homebrew

#export ZSH_HIGHLIGHT_HIGHLIGHTERS_DIR=$HOMEBREW_PATH/share/zsh-syntax-highlighting/highlighters

export PATH=$PATH:~/.bin

export PATH=$PATH:$(brew --prefix)/texlive/2022basic/bin/universal-darwin

export MYVIMRC=~$HOME/.vim/vimrc.vim

export ZSH_HIGHLIGHT_HIGHLIGHTERS_DIR=$(brew --prefix)/share/zsh-syntax-highlighting/highlighters

export HOMEBREW_NO_ANALYTICS=1

export LDFLAGS="-L/opt/homebrew/opt/llvm/lib"

export CPPFLAGS="-I/opt/homebrew/opt/llvm/include"

