# $HOME/.zshrc

echo ""
echo "------------------------------------------------"
echo "           melroser's dotfiles loaded           "
echo "------------------------------------------------"
echo ""
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
# test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

#  if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
#    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
# fi

#
# ZSH commands to execute at the start of an interactive session.
test -e /Users/melroser/.iterm2_shell_integration.zsh && source /Users/melroser/.iterm2_shell_integration.zsh || true
source $HOMEBREW_PATH/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
export ZSH_HIGHLIGHT_HIGHLIGHTERS_DIR=$HOMEBREW_PATH/share/zsh-syntax-highlighting/highlighters


$HOMEBREW_PATH/bin/neofetch

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
 if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
   source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
 fi


# cowsay -f
# it2attention fireworks
# echo "Tip of the day:"
# it2tip
# source $HOMEBREW_PATH/share/zsh-autosuggestions/zsh-autosuggestions.zsh
# source $HOMEBREW_PATH/share/zsh/site-functions/*
# source $HOMEBREW_PATH/share/zsh-completions/*
# source $HOMEBREW_PATH/share/zsh-fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
# source $HOMEBREW_PATH/share/zsh-history-substring-search/zsh-history-substring-search.zsh




export HISTFILESIZE=5000000
export HISTSIZE=5000000
setopt EXTENDED_HISTORY


if type brew &>/dev/null; then

    #autoload -Uz compinit
  #  compinit
  export ZSH_HIGHLIGHT_HIGHLIGHTERS_DIR=$(brew --prefix)/share/zsh-syntax-highlighting/highlighters
    source $(brew --prefix)/share/powerlevel10k/powerlevel10k.zsh-theme
    FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
    autoload -Uz promptinit
    promptinit
#    prompt p10k
fi

# Load Antigen
source $HOMEBREW_PATH/share/antigen/antigen.zsh
# source /usr/local/share/antigen/antigen.zsh

# Load Antigen configurations
antigen init ~/.antigenrc


# Tab completion matches lower and upper case
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'

# Source other zsh files

source ~/.aliases_zsh
source ~/.zshenv
# export PATH="/usr/local/opt/node@16/bin:$PATH"


# The next line updates PATH for the Google Cloud SDK.
# if [ -f '/Users/melroser/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/melroser/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
# if [ -f '/Users/melroser/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/melroser/Downloads/google-cloud-sdk/completion.zsh.inc'; fi


# export TRACE="$TRACE\n$BASH_SOURCE --> $(realpath $BASH_SOURCE)"
#export PATH="/usr/local/opt/node@16/bin:$PATH"


# Completions
# eval "$(op completion zsh)"; compdef _op op
#source /Users/melroser/.config/op/plugins.sh

# export PATH="$HOMEBREW_PATH/bin:$PATH"
# export PATH="/usr/local/opt/node@16/bin:$PATH"
#export PATH="$HOMEBREW_PATH/bin:$PATH"
# export PATH="$HOMEBREW_PATH/opt/openjdk/bin:$PATH"
# export PATH="$HOMEBREW_PATH/opt/openjdk/bin:$PATH"

# Completions
#  eval "$(op completion zsh)"; compdef _op op
# source $HOMEBREW_PATHshare/zsh/site-functions/async
# source $HOMEBREW_PATH/share/zsh/site-functions/_gh
# source $HOMEBREW_PATH/completions/zsh/_brew
# source $HOMEBREW_PATH/share/zsh/site-functions/_rg
# source $HOMEBREW_PATH/share/zsh/site-functions/_brew
# source $HOMEBREW_PATH/share/zsh/site-functions/_hugo
# source $HOMEBREW_PATH/share/zsh/site-functions/_poetry
# source $HOMEBREW_PATH/share/zsh/site-functions/_highlight
# source $HOMEBREW_PATH/share/zsh/site-functions/_yt-dlp
# source $HOMEBREW_PATH/share/zsh/site-functions/prompt_pure_setup
# source $HOMEBREW_PATH/opt/antigen/share/antigen/antigen.zsh
# source $HOMEBREW_PATH/opt/zsh-vi-mode/share/zsh-vi-mode/zsh-vi-mode.zsh
# source $HOMEBREW_PATH/share/zsh-you-should-use/you-should-use.plugin.zsh

# tabtab source for packages
# uninstall by removing these lines
#[[ -f ~/.config/tabtab/__tabtab.zsh ]] && . ~/.config/tabtab/__tabtab.zsh || true
# export PATH="/usr/local/opt/node@14/bin:$PATH"

#function hugoserver-1 {
#    cd ~/path/to/1
#    hugo server --buildDrafts --watch --verbose --source="/path/to/1" --config="/path/to/1/config.toml" --port=1377
#}
#
#function hugodeploy-1 {
#   cd /path/to/1
#   rm -rf /tmp/mysite.com
#   chmod -R 755 /path/to/1/static/
#   echo "GENERATING..."
#   hugo --config="/path/to/1/config.toml" --baseURL="http://mysite.com" -s /path/to/1/ -d /tmp/mysite.com
#   echo "SYNCING..."
#   /path/to/rsync -avz --delete --iconv=UTF-8-MAC,UTF-8 --exclude '.well-known' /tmp/mysite.com/ myuser@remote-web-host.com:/home/myuser/path/to/1
#}





# export PATH="/usr/local/opt/qt@5/bin:$PATH"

# The next line updates PATH for Netlify's Git Credential Helper.
test -f '/Users/melroser/Library/Preferences/netlify/helper/path.zsh.inc' && source '/Users/melroser/Library/Preferences/netlify/helper/path.zsh.inc'  source /Users/melroser/Library/Preferences/netlify/helper/path.zsh.inc 

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
#[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# source /usr/local/opt/zsh-vi-mode/share/zsh-vi-mode/zsh-vi-mode.plugin.zsh
# export PATH="/usr/local/opt/openjdk@11/bin:$PATH"

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

  # zsh
  source <(fzf --zsh)


# source $HOMEBREW_PATH/opt/chruby/share/chruby/chruby.sh
#  source $HOMEBREW_PATH/opt/chruby/share/chruby/auto.sh
#  chruby ruby-3.1.3

# export PATH="$HOMEBREW_PATH/opt/openjdk@11/bin:$PATH"
# export PATH="$HOMEBREW_PATH/opt/openjdk@11/bin:$PATH"
# export PATH="$HOMEBREW_PATH/opt/openjdk@11/bin:$PATH"
# export CPPFLAGS="-I$HOMEBREW_PATH/opt/openjdk@11/include"
# export LDFLAGS="-L$HOMEBREW_PATH/opt/libffi/lib"
# export CPPFLAGS="-I$HOMEBREW_PATH/opt/libffi/include"


# !! Contents within this block are managed by 'conda init' !!
# __conda_setup="$('/opt/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
# if [ $? -eq 0 ]; then
#     eval "$__conda_setup"
# else
#     if [ -f "/opt/anaconda3/etc/profile.d/conda.sh" ]; then
#         . "/opt/anaconda3/etc/profile.d/conda.sh"
#     else
#         export PATH="/opt/anaconda3/bin:$PATH"
#     fi
# fi
# unset __conda_setup

# source ~/.flutter_tools.sh

# neofetch
#
#
#source $HOMEBREW_PATH/share/zsh/site-functions/./*

# export PATH=/usr/local/anaconda3/bin:$PATH
# export PATH=$HOMEBREW_PATH/anaconda3/bin:$PATH
# source $HOMEBREW_PATH/share/powerlevel10k/powerlevel10k.zsh-theme

# source  $HOMEBREW_PATH/share/zsh-autosuggestions/zsh-autosuggestions.zsh
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
#[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

#export PATH="$HOMEBREW_PATH/opt/llvm/bin:$PATH"
