# $HOME/.zshrc

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
# test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

#  if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
#    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
# fi

#
# ZSH commands to execute at the start of an interactive session.
test -e /Users/melroser/.iterm2_shell_integration.zsh && source /Users/melroser/.iterm2_shell_integration.zsh || true
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
export ZSH_HIGHLIGHT_HIGHLIGHTERS_DIR=/opt/homebrew/share/zsh-syntax-highlighting/highlighters


echo ""
echo "------------------------------------------------"
echo "           melroser's dotfiles loaded           "
echo "------------------------------------------------"
echo ""
# cowsay -f
# it2attention fireworks
# echo "Tip of the day:"
# it2tip

/opt/homebrew/bin/neofetch

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
 if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
   source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
 fi

export ZSH_HIGHLIGHT_HIGHLIGHTERS_DIR=/opt/homebrew/share/zsh-syntax-highlighting/highlighters
# source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
# source /opt/homebrew/share/zsh/site-functions/*
# source /opt/homebrew/share/zsh-completions/*
# source /opt/homebrew/share/zsh-fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
# source /opt/homebrew/share/zsh-history-substring-search/zsh-history-substring-search.zsh




export HISTFILESIZE=5000000
export HISTSIZE=5000000
setopt EXTENDED_HISTORY


if type brew &>/dev/null; then

    FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
    autoload -Uz compinit
    compinit

    autoload -U promptinit;
    prompt p10k
fi

# Load Antigen
source /opt/homebrew/share/antigen/antigen.zsh
# source /usr/local/share/antigen/antigen.zsh

# Load Antigen configurations
antigen init ~/.antigenrc


# Tab completion matches lower and upper case
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'

# Source other zsh files

source ~/.aliases_zsh
source ~/.zshenv
# export PATH="/usr/local/opt/node@16/bin:$PATH"


# The next line updates PATH for the Google Cloud SDK.
# if [ -f '/Users/melroser/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/melroser/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
# if [ -f '/Users/melroser/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/melroser/Downloads/google-cloud-sdk/completion.zsh.inc'; fi


# export TRACE="$TRACE\n$BASH_SOURCE --> $(realpath $BASH_SOURCE)"
#export PATH="/usr/local/opt/node@16/bin:$PATH"


# Completions
# eval "$(op completion zsh)"; compdef _op op
#source /Users/melroser/.config/op/plugins.sh

# export PATH="/opt/homebrew/bin:$PATH"
# export PATH="/usr/local/opt/node@16/bin:$PATH"
#export PATH="/opt/homebrew/bin:$PATH"
# export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"
# export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"

# Completions
#  eval "$(op completion zsh)"; compdef _op op
# source /opt/homebrew/share/zsh/site-functions/async
# source /opt/homebrew/share/zsh/site-functions/_gh
# source /opt/homebrew/completions/zsh/_brew
# source /opt/homebrew/share/zsh/site-functions/_rg
# source /opt/homebrew/share/zsh/site-functions/_brew
# source /opt/homebrew/share/zsh/site-functions/_hugo
# source /opt/homebrew/share/zsh/site-functions/_poetry
# source /opt/homebrew/share/zsh/site-functions/_highlight
# source /opt/homebrew/share/zsh/site-functions/_yt-dlp
# source /opt/homebrew/share/zsh/site-functions/prompt_pure_setup
# source /opt/homebrew/opt/antigen/share/antigen/antigen.zsh
# source /opt/homebrew/opt/zsh-vi-mode/share/zsh-vi-mode/zsh-vi-mode.zsh
# source /opt/homebrew/share/zsh-you-should-use/you-should-use.plugin.zsh

# tabtab source for packages
# uninstall by removing these lines
#[[ -f ~/.config/tabtab/__tabtab.zsh ]] && . ~/.config/tabtab/__tabtab.zsh || true
# export PATH="/usr/local/opt/node@14/bin:$PATH"

#function hugoserver-1 {
#    cd ~/path/to/1
#    hugo server --buildDrafts --watch --verbose --source="/path/to/1" --config="/path/to/1/config.toml" --port=1377
#}
#
#function hugodeploy-1 {
#   cd /path/to/1
#   rm -rf /tmp/mysite.com
#   chmod -R 755 /path/to/1/static/
#   echo "GENERATING..."
#   hugo --config="/path/to/1/config.toml" --baseURL="http://mysite.com" -s /path/to/1/ -d /tmp/mysite.com
#   echo "SYNCING..."
#   /path/to/rsync -avz --delete --iconv=UTF-8-MAC,UTF-8 --exclude '.well-known' /tmp/mysite.com/ myuser@remote-web-host.com:/home/myuser/path/to/1
#}





# export PATH="/usr/local/opt/qt@5/bin:$PATH"

# The next line updates PATH for Netlify's Git Credential Helper.
test -f '/Users/melroser/Library/Preferences/netlify/helper/path.zsh.inc' && source '/Users/melroser/Library/Preferences/netlify/helper/path.zsh.inc'  source /Users/melroser/Library/Preferences/netlify/helper/path.zsh.inc 

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
#[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# source /usr/local/opt/zsh-vi-mode/share/zsh-vi-mode/zsh-vi-mode.plugin.zsh
# export PATH="/usr/local/opt/openjdk@11/bin:$PATH"

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

  # zsh
  source <(fzf --zsh)


 source /opt/homebrew/opt/chruby/share/chruby/chruby.sh
 source /opt/homebrew/opt/chruby/share/chruby/auto.sh
 chruby ruby-3.1.3

# export PATH="/opt/homebrew/opt/openjdk@11/bin:$PATH"
# export PATH="/opt/homebrew/opt/openjdk@11/bin:$PATH"
# export PATH="/opt/homebrew/opt/openjdk@11/bin:$PATH"
# export CPPFLAGS="-I/opt/homebrew/opt/openjdk@11/include"
# export LDFLAGS="-L/opt/homebrew/opt/libffi/lib"
# export CPPFLAGS="-I/opt/homebrew/opt/libffi/include"


# !! Contents within this block are managed by 'conda init' !!
# __conda_setup="$('/opt/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
# if [ $? -eq 0 ]; then
#     eval "$__conda_setup"
# else
#     if [ -f "/opt/anaconda3/etc/profile.d/conda.sh" ]; then
#         . "/opt/anaconda3/etc/profile.d/conda.sh"
#     else
#         export PATH="/opt/anaconda3/bin:$PATH"
#     fi
# fi
# unset __conda_setup

# source ~/.flutter_tools.sh

# neofetch
#
#
#source /opt/homebrew/share/zsh/site-functions/.*

# export PATH=/usr/local/anaconda3/bin:$PATH
# export PATH=/opt/homebrew/anaconda3/bin:$PATH
source /opt/homebrew/share/powerlevel10k/powerlevel10k.zsh-theme

source  /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
# [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
